# Generated by Django 4.2.30 on 2026-06-03 05:29

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('ilimitado', 'Ilimitado')], default='basico', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=True)),
                ('mensaje_bienvenida', models.TextField(blank=True, default='Hemos recibido tu equipo. Te notificaremos en cada etapa de la reparación.')),
            ],
            options={
                'verbose_name': 'Taller (Tenant)',
                'verbose_name_plural': 'Talleres (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.taller')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
